### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Gapstare** [awesomekling/serenity#1]
> Undecided. Probably something close to 2-clause BSD.

If you are using GPL code you can't just relicence them as BSD, see elf.h .

**Comment by awesomekling** [comment]
Thank you, my vigilant friend. I've replaced it with a version from OpenBSD for now. It's 3-clause-BSD but at least it's not GPL.

https://github.com/awesomekling/serenity/commit/d11b5407a39a24cfd2b67ab5bf83a7e672e8ebba
