### ISSUE TITLE
Create helper to parse /proc/all

### ISSUE THREAD

**Issue by GuillaumeGas** [awesomekling/serenity#34]
We need sometimes to use paths like `/proc/all` (see source code of pidof, killall...).
It would be nice to make a helper function that everyone can use instead of manually using it everywhere.

This helper could be used to retrieve a `String` or directly a `CFile`.

**Comment by awesomekling** [comment]
I think we should have a helper function that can parse /proc/all and return all the information in a single object.

**Comment by GuillaumeGas** [comment]
Does something is missing to close this issue ?

**Comment by awesomekling** [comment]
Ah no, we can close it! Thank you :)
